### ISSUE TITLE
I can't find the main code for dm in the main file

### ISSUE THREAD

**Issue by KeNichY07** [Jameison-Tech/DisxoesMassdmbot#3]
Where is the code for dming all the member?
I think there should be a => `message.guild.members.cache.forEach` command.
Will it work without it?

**Comment by Jameison-Tech** [comment]
ye it’s discontinued anyway so

**Comment by KeNichY07** [comment]
Nevermind. Found the same bot from another person 😛

**Comment by Jameison-Tech** [comment]
kek
